functions:
  'test':
    command: shell.exec
    params:
      working_dir: src
      script: |
        if [ -s "$HOME/.rvm/scripts/rvm" ] ; then
          export PATH="$PATH:$HOME/.rvm/bin"
          bash -s source "$HOME/.rvm/scripts/rvm"
        elif [ -s "/usr/local/rvm/scripts/rvm" ] ; then
          export PATH="$PATH:/usr/local/rvm/bin"
          bash -s source "/usr/local/rvm/scripts/rvm"
        else
          command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
          curl -sSL https://get.rvm.io | bash -s stable --auto-dotfiles
          export PATH="$PATH:$HOME/.rvm/bin"
          bash -s source "$HOME/.rvm/scripts/rvm"
        fi
        rvm install ruby-2.3.0
        rvm use 2.3.0
        gem install bundler
        bundle install
        bundle exec rake clean
        bundle exec rake compile
        bundle exec rake spec

tasks:
  - name: 'build'
    commands:
      - command: git.get_project
        params:
          directory: src
      - func: 'test'

buildvariants:
  - name: debian
    display_name: Debian 8.1 x86
    run_on:
      - debian81-test
    tasks:
      - name: 'build'
  - name: rhelzseries
    display_name: RHEL 7.2 Z-Series
    run_on:
      - rhel72-zseries-test
    tasks:
      - name: 'build'
  - name: rhelpower
    display_name: RHEL 7.1 PowerPC
    run_on:
      - rhel71-power8-test
    tasks:
      - name: 'build'
