functions:
  'install rvm':
    command: shell.exec
    params:
      working_dir: src
      script: |
        if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
          source "$HOME/.rvm/scripts/rvm"
        elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
          source "/usr/local/rvm/scripts/rvm"
        else
          command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
          curl -sSL https://get.rvm.io | bash -s stable --auto-dotfiles
          bash -s . "$HOME/.profile"
        fi
  'install ruby':
    command: shell.exec
    params:
      working_dir: src
      script: |
        rvm install ruby-2.3.0
  'use ruby standard':
    command: shell.exec
    params:
      working_dir: src
      script: |
        rvm use 2.3.0
  'use ruby pps':
    command: shell.exec
    params:
      working_dir: src
      script: |
        bash --login -s rvm use 2.3.0
  'install bundler':
    command: shell.exec
    params:
      working_dir: src
      script: |
        gem install bundler
  'install dependencies':
    command: shell.exec
    params:
      working_dir: src
      script: |
        bundle install
  'clean project':
    command: shell.exec
    params:
      working_dir: src
      script: |
        bundle exec rake clean
  'compile':
    command: shell.exec
    params:
      working_dir: src
      script: |
        bundle exec rake compile
  'run specs':
    command: shell.exec
    params:
      working_dir: src
      script: |
        bundle exec rake spec

tasks:
  - name: checkout
    commands:
      - command: git.get_project
        params:
          directory: src
  - name: rvm
    depends_on:
      - name: checkout
    commands:
      - func: 'install rvm'
  - name: rubystandard
    depends_on:
      - name: rvm
    commands:
      - func: 'install ruby'
      - func: 'use ruby standard'
  - name: rubyppc
    depends_on:
      - name: rvm
    commands:
      - func: 'install ruby'
      - func: 'use ruby ppc'
  - name: bundler
    depends_on:
      - name: ruby
    commands:
      - func: 'install bundler'
      - func: 'install dependencies'
  - name: clean
    depends_on:
      - name: bundler
    commands:
      - func: 'clean project'
  - name: compile
    depends_on:
      - name: clean
    commands:
      - func: 'compile'
  - name: rspec
    depends_on:
      - name: compile
    commands:
      - func: 'run specs'

buildvariants:
  - name: ubuntu
    display_name: Ubuntu 14.10 x86
    run_on:
      - ubuntu1410-test
    tasks:
      - name: checkout
      - name: rvm
      - name: rubystandard
      - name: bundler
      - name: clean
      - name: compile
      - name: rspec
  - name: rhelzseries
    display_name: RHEL 7.2 Z-Series
    run_on:
      - rhel72-zseries-test
    tasks:
      - name: checkout
      - name: rvm
      - name: rubystandard
      - name: bundler
      - name: clean
      - name: compile
      - name: rspec
  - name: rhelpower
    display_name: RHEL 7.1 PowerPC
    run_on:
      - rhel71-power8-test
    tasks:
      - name: checkout
      - name: rvm
      - name: rubyppc
      - name: bundler
      - name: clean
      - name: compile
      - name: rspec
