functions:
  'install rvm':
    command: shell.exec
    params:
      working_dir: src
      script: |
        if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
          source "$HOME/.rvm/scripts/rvm"
        elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
          source "/usr/local/rvm/scripts/rvm"
        else
          gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
          \curl -sSL https://get.rvm.io | bash -s stable
          source ~/.profile
        fi
  'install ruby':
    command: shell.exec
    params:
      working_dir: src
      script: |
        rvm install ruby-2.3.0
  'use ruby':
    command: shell.exec
    params:
      working_dir: src
      script: |
        rvm use 2.3.0
  'install bundler':
    command: shell.exec
    params:
      working_dir: src
      script: |
        gem install bundler
  'install dependencies':
    command: shell.exec
    params:
      working_dir: src
      script: |
        bundle install
  'clean project':
    command: shell.exec
    params:
      working_dir: src
      script: |
        bundle exec rake clean
  'compile and run specs':
    command: shell.exec
    params:
      working_dir: src
      script: |
        bundle exec rake

tasks:
  - name: build
    commands:
      - command: git.get_project
        params:
          directory: src
      - func: 'use ruby'
      - func: 'install bundler'
      - func: 'install dependencies'
      - func: 'clean project'
      - func: 'compile and run specs'

buildvariants:
  - name: ubuntu
    display_name: Ubuntu
    run_on:
      - ubuntu1604-test
    tasks:
      - name: build
