functions:
  'install rvm':
    command: shell.exec
    params:
      working_dir: src
      script: |
        if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
          source "$HOME/.rvm/scripts/rvm"
        elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
          source "/usr/local/rvm/scripts/rvm"
        else
          command curl -sSL https://rvm.io/mpapis.asc | gpg --import -
          curl -sSL https://get.rvm.io | bash -s stable --auto-dotfiles
        fi
  'source rvm ubuntu':
    command: shell.exec
    params:
      working_dir: src
      script: |
        export PATH="$PATH:$HOME/.rvm/bin"
        [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
  'source rvm default':
    command: shell.exec
    params:
      working_dir: src
      script: |
        bash -s . "$HOME/.profile"
  'install ruby':
    command: shell.exec
    params:
      working_dir: src
      script: |
        rvm install ruby-2.3.0
  'use ruby':
    command: shell.exec
    params:
      working_dir: src
      script: |
        rvm use 2.3.0
  'install bundler':
    command: shell.exec
    params:
      working_dir: src
      script: |
        gem install bundler
  'install dependencies':
    command: shell.exec
    params:
      working_dir: src
      script: |
        bundle install
  'clean project':
    command: shell.exec
    params:
      working_dir: src
      script: |
        bundle exec rake clean
  'compile':
    command: shell.exec
    params:
      working_dir: src
      script: |
        bundle exec rake compile
  'run specs':
    command: shell.exec
    params:
      working_dir: src
      script: |
        bundle exec rake spec

tasks:
  - name: 'build-zseries'
    commands:
      - command: git.get_project
        params:
          directory: src
      - func: 'install rvm'
      - func: 'source rvm default'
      - func: 'install ruby'
      - func: 'use ruby'
      - func: 'install bundler'
      - func: 'install dependencies'
      - func: 'clean project'
      - func: 'compile'
      - func: 'run specs'
  - name: 'build-ppc'
    commands:
      - command: git.get_project
        params:
          directory: src
      - func: 'install rvm'
      - func: 'source rvm default'
      - func: 'install ruby'
      - func: 'use ruby'
      - func: 'install bundler'
      - func: 'install dependencies'
      - func: 'clean project'
      - func: 'compile'
      - func: 'run specs'
  - name: 'build-ubuntu'
    commands:
      - command: git.get_project
        params:
          directory: src
      - func: 'install rvm'
      - func: 'source rvm ubuntu'
      - func: 'install ruby'
      - func: 'use ruby'
      - func: 'install bundler'
      - func: 'install dependencies'
      - func: 'clean project'
      - func: 'compile'
      - func: 'run specs'

buildvariants:
  - name: ubuntu
    display_name: Ubuntu 14.10 x86
    run_on:
      - ubuntu1410-test
    tasks:
      - name: 'build-ubuntu'
  - name: rhelzseries
    display_name: RHEL 7.2 Z-Series
    run_on:
      - rhel72-zseries-test
    tasks:
      - name: 'build-zseries'
  - name: rhelpower
    display_name: RHEL 7.1 PowerPC
    run_on:
      - rhel71-power8-test
    tasks:
      - name: 'build-ppc'
