language: ruby

sudo: false

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3.0
  - ruby-head
  - jruby-19mode
  - jruby-9.1.5.0
  - jruby-head
  - rbx-2.5.2

jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8

env: CI="travis"

notifications:
  email: false
  flowdock: 1da4416b8ff98d1880986472428b1b1b

branches:
  only:
    - master
    - 2.x-stable

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2.5.2
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
      env: CI="travis"
    - rvm: 1.9.3
      jdk: oraclejdk8
      env: CI="travis"
    - rvm: 2.0.0
      jdk: openjdk7
      env: CI="travis"
    - rvm: 2.0.0
      jdk: oraclejdk8
      env: CI="travis"
    - rvm: 2.1
      jdk: openjdk7
      env: CI="travis"
    - rvm: 2.1
      jdk: oraclejdk8
      env: CI="travis"
    - rvm: 2.2
      jdk: openjdk7
      env: CI="travis"
    - rvm: 2.2
      jdk: oraclejdk8
      env: CI="travis"
    - rvm: 2.3
      jdk: openjdk7
      env: CI="travis"
    - rvm: 2.3
      jdk: oraclejdk8
      env: CI="travis"
    - rvm: ruby-head
      jdk: openjdk7
      env: CI="travis"
    - rvm: ruby-head
      jdk: oraclejdk8
      env: CI="travis"
    - rvm: rbx-2.5.2
      jdk: openjdk7
      env: CI="travis"
    - rvm: rbx-2.5.2
      jdk: oraclejdk8
      env: CI="travis"
