language: ruby

sudo: false

before_install:
  - gem install bundler

rvm:
  - 1.9.3
  - 2.4.2
  - ruby-head
  - jruby-19mode
  - jruby-9.1.12.0

env: CI="travis"

notifications:
  email: false
  flowdock: 1da4416b8ff98d1880986472428b1b1b

branches:
  only:
    - master
    - 5.0-dev

matrix:
  allow_failures:
    - rvm: ruby-head